name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise un runner GitHub Actions basé sur Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Récupère le code source

      - name: Deploy to EC2
        uses: appleboy/scp-action@master  # Utilise l'action pour copier des fichiers via SCP
        with:
          host: ec2-54-160-219-241.compute-1.amazonaws.com  # Remplacez par l'adresse de l'instance EC2
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # La clé privée SSH, à ajouter comme secret dans le dépôt GitHub
          source: "."  # Tous les fichiers du projet
          target: "/home/ubuntu/projet8_dash"  # Répertoire cible sur l'EC2

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master  # Utilise l'action pour exécuter des commandes SSH
        with:
          host: ec2-54-160-219-241.compute-1.amazonaws.com # Remplacez par l'adresse de l'instance EC2
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/projet8_dash  
            git pull origin main  # Mettre à jour avec la dernière version du dépôt
            cd mep_dash # Accède au sous-dossier mep_dash
            #docker-compose down # Arrête les conteneurs existants
            #docker-compose up   # Redémarre les conteneurs en mode détaché
