name: Deploy to EC2

on:
  push:
    branches: [ main ]  # Déclenche le workflow sur les push vers la branche main
    paths:
      - 'projet8_dash/**'  # Se déclenche pour tout changement dans le dossier projet8_dash

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu GitHub Runner
    
    steps:
    # Étape 1 : Checkout du code
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer SSH
    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/github-action
        chmod 600 ~/.ssh/github-action
        echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts

    # Étape 3 : Se connecter et déployer sur l'instance EC2
    - name: Deploy to EC2
      env:
        HOST: ec2-54-160-219-241.compute-1.amazonaws.com  # Adresse IP publique de votre instance EC2
        USERNAME: ec2-user  # Utilisateur correct
      run: |
        ssh -i ~/.ssh/github-action $USERNAME@$HOST '
          cd ~/projet8_dash  # Accède à la racine du projet
          git pull  # Met à jour le code depuis GitHub
          cd mep_dash  # Accède au sous-dossier mep_dash
          docker-compose down  # Arrête les conteneurs existants
          docker-compose up   # Redémarre les conteneurs en mode détaché
        '

